version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/included:13.1.0
    working_directory: ~/repo

jobs:
  test:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  test-workflow:
    jobs:
      - test
