version: 2.1

executors:
  node-executor:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107-ff106
    working_directory: ~/app

jobs:
  test:
    executor: node-executor
    steps:
      - run:
          name: Checkout via HTTPS
          command: |
            git clone https://github.com/PirogovValerii/CypressGoals.git .
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
